language: rust

rust:
  - nightly
  - beta
  - stable

script:
  - cargo test
  - cargo check --no-default-features

matrix:
  include:
    - rust: 1.34.0
      script: cargo check
    - rust: 1.36.0
      script: cargo check --no-default-features
    - name: Clippy
      install:
        - CLIPPY_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)
        - echo "Latest nightly with Clippy is $CLIPPY_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$CLIPPY_NIGHTLY"
        - rustup component add clippy
      script:
        - cargo clippy -- -Dclippy::all
