[package]
name = "color-spantrace"
version = "0.1.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-error = "0.1.2"
tracing-core = "0.1.10"
ansi_term = "0.12.1"

[dev-dependencies]
tracing-subscriber = "0.2.5"
tracing = "0.1.13"
